# ITEM/AMOUNT
chimichanga { type = smoke, input = BURRITO, output = CHIMICHANGA }

cooked_pufferfish { type = smoke, input = PUFFERFISH, output = COOKED_PUFFERFISH }

pork_rinds { type = smoke, input = COOKED_PORKCHOP, output = PORK_RINDS, cookTime = 5s }

cooked_goat { type = smoke, input = RAW_GOAT, output = COOKED_GOAT }

cooked_frog_leg_cold { type = smoke, input = FROG_LEG_COLD, output = COOKED_FROG_LEG }

cooked_frog_leg_warm { type = smoke, input = FROG_LEG_WARM, output = COOKED_FROG_LEG }

cooked_frog_leg_temperate { type = smoke, input = FROG_LEG_TEMPERATE, output = COOKED_FROG_LEG }

pizza { type = smoke, input = RAW_PIZZA, output = PIZZA }

bread { type = smoke, input = DOUGH, output = BREAD }

coffee_beans_cooked { type = smoke, input = COFFEE_BEANS, output = COFFEE_BEANS_COOKED }

coffee_beans_roasted { type = smoke, input = COFFEE_BEANS_COOKED, output = COFFEE_BEANS_ROASTED }

coffee_beans_dark_roast { type = smoke, input = COFFEE_BEANS_ROASTED, output = COFFEE_BEANS_DARK_ROAST }